name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: Build Env
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      env: # Or as an environment variable
        CREDS: ${{ secrets.CREDS }}
        Spreadsheet: ${{ secrets.SPREADSHEET }}
        Title: ${{ secrets.TITLE }}
      run: |
        npm install --global yarn
        yarn
        mkdir cron/data
        echo '[]' >> cron/data/players-new.json
        mkdir cron/logs
        touch cron/logs/log.txt
        ./cron/run.sh
        npm run build
